version: '3'
services:

  service:
    image: hack4law.azurecr.io/hack4law-assistant-service:0.0.7-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hack4law
      - SPRING_DATASOURCE_USERNAME=hack4law
      - SPRING_DATASOURCE_PASSWORD=123ewqasd
      - HACK4LAW_SERVICE_CORS_ALLOWED_ORIGIN=*
      - HACK4LAW_SERVICE_CORS_ALLOWED_HEADER=*
      - HACK4LAW_SERVICE_CORS_ALLOWED_METHOD=*
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:14-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123ewqasd
      - POSTGRES_USER=hack4law
      - POSTGRES_DB=hack4law
    ports:
      - "5432:5432"

volumes:
  pg_data:
