version: '3'
services:

  service:
    image: hack4law.azurecr.io/hack4law-assistant-service:0.0.2-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - AUTH_USER=hack4law
      - AUTH_PASSWORD=d95DaH34jcoP
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hack4law.postgres.database.azure.com:5432/postgres
      - SPRING_DATASOURCE_USERNAME=hack4law
      - SPRING_DATASOURCE_PASSWORD=zkw8GRO7omaO
      - HACK4LAW_SERVICE_CORS_ALLOWED_ORIGIN=*
      - HACK4LAW_SERVICE_CORS_ALLOWED_HEADER=*
      - HACK4LAW_SERVICE_CORS_ALLOWED_METHOD=*
